name: info_x
version: 0.8.0+3
homepage: https://github.com/ericmartineau/info_x
description: A new Flutter package project.
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  timezone: ^0.9.1
  dartxx: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
